services:
  internet-os:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - port: 6901
        protocol: http
    volumes:
      - persistent:/persist

volumes:
  persistent:
    provider: local